site_name: Momentum
nav:
  - Admin Guide: index.md
  - Release Notes: about.md

theme:
  name: readthedocs
  extra_footer: "Your custom footer content goes here."
  color_mode: light
  user_color_mode_toggle: true
  nav_style: dark
  locale: en
  palette:
    scheme: slate
    primary: green
